pipeline {
    agent any

    environment {
        COLLECTION = "api-test-tools/postman/PetStoreDemo.json"
        REPORT_DIR = "reports/newman-${BUILD_NUMBER}"
        REPORT_HTML = "index.html"
    }

    stages {
        stage('Verify Node.js Installation') {
            steps {
                echo 'Checking Node.js and npm availability...'
                sh '''
                node -v || { echo "Node.js is not installed!"; exit 1; }
                npm -v || { echo "npm is not installed!"; exit 1; }
                '''
            }
        }

        stage('Install Newman') {
            steps {
                echo 'Installing Newman and HTML reporter...'
                sh 'npm install -g newman newman-reporter-htmlextra'
            }
        }

        stage('Run Postman Tests') {
            steps {
                echo "Running Postman tests from ${env.COLLECTION}..."
                sh """
                    mkdir -p ${REPORT_DIR}
                    newman run "${COLLECTION}" \
                    --reporters cli,htmlextra \
                    --reporter-htmlextra-export "${REPORT_HTML}"
                    """
            }
        }
    }

    post {
        success {
            echo "✅ All tests executed successfully!"
        }
        failure {
            echo "❌ Some tests failed. Check the report for details."
        }
        always {
            echo 'Archiving HTML report...'
            archiveArtifacts artifacts: "${env.REPORT_HTML}", allowEmptyArchive: true

            // Publish the HTML report so it’s clickable in the Jenkins UI
            publishHTML(target: [
                reportDir: "${REPORT_DIR}",                 // Report is in workspace root
                reportFiles: "${REPORT_HTML}" ,      ,  // Report file
                reportName: "Newman Test Report",
                keepAll: true,
                allowMissing: false,
                alwaysLinkToLastBuild: true
            ])
        }
    }
}
